#!/usr/bin/env python2
# -*- coding: utf-8 -*-

"""
The Done!Tools are a collection of tools to handle task and events.


doto add  "Title" "descripton"
doto ls
doto

"""

import argparse
import blessings
import cli
import cli.cmd
import importlib
import pkgutil
import defaultconfig
import sys
import task
import util


EXIT_CODES = util.enum(unknown_cmd=1)


def import_commands():
    """Import all commands dynamicylly from cli.cmd."""
    commands = {}
    for _, modname, ispkg in pkgutil.iter_modules(cli.cmd.__path__, cli.cmd.__name__ + "."):
        if ispkg is False:
            module = importlib.import_module(modname)
            commands[module.COMMAND] = module
    return commands


def init_env(commands):
    """
    Initialize the enviroment.

    This includes
        - the config and it default values,
        - the parser and subpurser,
        - and the enviroment variables.

    @param commands the modules of the cli commands

    """
    config = defaultconfig.read_config()
    parser = argparse.ArgumentParser(prog="doto", description="The Done!Tools are a collection of tools to handle task and events.")
    subparsers = parser.add_subparsers(help='command', dest="cmd")
    for cmd in commands:
        cmd.init_parser(subparsers)
    args = parser.parse_args()

    return args, config


def main():
    """
    The main function.

    It initialises the eviroment,
    parses the command line arguments,
    and executes the gvien command.

    """

    # Init phase
    cmds = import_commands()
    args, config = init_env(cmds.values())
    cli.parser.set_date_parser(config.date.local_tz, config.date.cli_input_str)
    term = blessings.Terminal()
    with task.Store(config.path.store, config.path.cache) as store:
        # execute command
        exit_code = cmds[args.cmd].main(store, args, config, term)
    sys.exit(exit_code)

if __name__ == "__main__":
    main()
