#!/bin/sh

rm_if_there() {
    file="$1"
    if [ -e "$file" ]; then
        rm "$file"
    fi
}

rm_if_there ./test/store/cache
rm_if_there ./test/store/doto.db
rm_if_there ./test/store/doto2.db

nosetests &&
DOTO="python3 -m doto" roundup test/doto-cli-test.sh
